# Generated by Django 4.1.7 on 2023-11-27 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County_Health_Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerID', models.IntegerField(null=True)),
                ('fullName', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_ID', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='medication_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageID', models.IntegerField(null=True)),
                ('medicationName', models.CharField(max_length=255, null=True)),
                ('batchNumber', models.CharField(max_length=255, null=True)),
                ('expiryDate', models.DateField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Delivered', 'Delivered')], max_length=255, null=True)),
                ('Institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.institution')),
                ('county_Health_Worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.county_health_worker')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.institution')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.medication_package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.medicationdistribution')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorID', models.IntegerField(null=True)),
                ('auditorName', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
