# Generated by Django 4.1.7 on 2023-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_medication_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication_package',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
