# Generated by Django 4.1.7 on 2023-11-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_medication_package_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication_package',
            name='packageID',
        ),
    ]
