# Generated by Django 4.1.7 on 2023-11-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_medication_package_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication_package',
            name='Institution',
        ),
    ]
